### ISSUE TITLE
Engineering Wormholes

### ISSUE THREAD

**Issue by Mahuada** [Justw8/TeleportMenu#1]
This is great one ! Just want to check will you plan to add wormhole toys into this list?

**Comment by Justw8** [comment]
yep, engineering items are on the to-do! added mage portals today. 
Might take some time due to the expansion launching though and started working on this a bit last minute while setting up my characters for the expansion (lol).

**Comment by Justw8** [comment]
I added them with individual icons for now, will merge them into a flyout at a later time!

thanks for the interest and support.
