### ISSUE TITLE
Add text to the dungeon portals

### ISSUE THREAD

**Issue by kayti-wow** [Justw8/TeleportMenu#10]
Having to memorise the icons or hover over and read the text is quite annoying.  Any chance you can add the established abbreviations for each dungeon as text over the icon?

e.g. 
Necrotic Wake either "Wake" or "NW" would work
Mists of Tirna Scithe should be "Mists" or even just "M"

**Comment by Justw8** [comment]
I'll add this when I have a settings menu so you can toggle it on and off, good idea!
