### ISSUE TITLE
v5.1 Engineering Wormholes menu did not appear.

### ISSUE THREAD

**Issue by BlueNightSky** [Justw8/TeleportMenu#11]
I have many toys of engineering Wormholes, but the menu has not appeared at all.

**Comment by Justw8** [comment]
Do you also have engineering? can you show me both a toy in your toy list (hover over) and the menu? I do a `IsToyUsable` check which should fail if you do not meet the engineering requirements.

**Comment by DeltaSevenEngineer** [comment]
Latest update is also no longer showing the Engineering wormholes for me on my Belf Paladin, who has been an Engineer since Cata. Screenshots attached.

![WoWScrnShot_082424_120448](https://github.com/user-attachments/assets/79b5c2d7-960f-4e69-96c5-2a98bbb10504)
![WoWScrnShot_082424_120454](https://github.com/user-attachments/assets/e30dbf7a-b3ee-4599-8198-5f65d86db1b0)

**Comment by DeltaSevenEngineer** [comment]
Interestingly, when I logged over to my Priest, who only has Shadowlands Engineering, his wormhole shows up. Logging back over to my Paladin now shows the Engineer option but only the Shadowlands wormhole. None of the others appear.
![WoWScrnShot_082424_121248](https://github.com/user-attachments/assets/87db2347-d955-4e68-98ad-d676f0cca1f5)

**Comment by Justw8** [comment]
Could you run:
```/dump C_ToyBox.IsToyUsable(48933)```

you can replace the number with others here:
```
	[48933]  Wormhole Generator: Northrend
	[87215]  Wormhole Generator: Pandaria
	[112059]  Wormhole Centrifuge (Dreanor)
	[151652]  Wormhole Generator: Argus
	[168807]  Wormhole Generator: Kul Tiras
	[168808]  Wormhole Generator: Zandalar
	[172924]  Wormhole Generator: Shadowlands
	[221966]  Wormhole Generator: Khaz Algar
	```

**Comment by DeltaSevenEngineer** [comment]
![WoWScrnShot_082424_121643](https://github.com/user-attachments/assets/fbd392a7-4fbc-4017-ae62-d7075bf0ef49)

Reloading after now has those specific ones I ran appearing.

![WoWScrnShot_082424_121853](https://github.com/user-attachments/assets/0c03b031-2590-42d1-8615-37b45400e033)

**Comment by DeltaSevenEngineer** [comment]
I pulled up the ID's for the other Engineering teleports:

Goblin Engineering
Dimensional Ripper - Area 52 (30542)
Dimensional Ripper - Everlook (18984)

Gnomish Engineering
Ultrasafe Transporter: Gadgetzan (18986)
Ultrasafe Transporter: Toshley's Station (30544)

Wyrmhole Generator: Dragon Isles (198156)

**Comment by Justw8** [comment]
Do they remain too after you restart the game? (reloading/restarting isn't fully the same)

**Comment by DeltaSevenEngineer** [comment]
After restarting the Engineering menu is gone again.

**Comment by Justw8** [comment]
@DeltaSevenEngineer I've added a slight delay on login, please let me know if that resolves things on login. (in the alpha, don't want to tag unless confirmed helping)

**Comment by DeltaSevenEngineer** [comment]
Working but only after I reload once.

**Comment by Justw8** [comment]
:( I'll try to see what can be improved more. Don't have the issue myself so annoying to check.

**Comment by Justw8** [comment]
Trying a longer delay (from 0,.5s to 3s, should be fine on login) and added Blizzard_Collections as a dependency (no idea if it has an effect, but worth a shot!)

**Comment by BlueNightSky** [comment]
v5.1-2-gcee46bf is works, Now normally display my 7 wormhole toys. Thank you!
