### ISSUE TITLE
Reverse Order Of Mage Portals/Teleports (Default Or Option)

### ISSUE THREAD

**Issue by zwang180** [Justw8/TeleportMenu#15]
Hi there,

First of all, awesome addon! I'd like to request a feature where the sorting order of mage portals/teleports to be reversed (can be the default or through an option), at the moment to portal/teleport to the city of the latest expansion is all the way to the very right. The problem here is that the portals/teleports menu is shown on hover and it's very easy to move outside when I'm moving my cursor to the far right side. IMHO it'd make more sense to have the city of the latest expansion located at the very left since it'd likely be used more frequently.

In any case, thank you very much for your time creating this addon!

**Comment by Justw8** [comment]
Sounds easy enough to add, although I will keep this on the todo until after I add an option menu - don't want this to be controlled by chat commands.

**Comment by zwang180** [comment]
> Sounds easy enough to add, although I will keep this on the todo until after I add an option menu - don't want this to be controlled by chat commands.

Makes total sense, thanks for the swift reply!

**Comment by Justw8** [comment]
This was added, closing now.
