### ISSUE TITLE
Suggestion: Menu for teleport items

### ISSUE THREAD

**Issue by Ikatzuki** [Justw8/TeleportMenu#2]
Would be cool to have a menu that also includes the various [teleport items](https://wowpedia.fandom.com/wiki/Teleport#Teleport_items) that exists in the game. I use things like Jaina's Locket quite often!

There's also some random toys like [Fractured Necrolyte Skull](https://www.wowhead.com/item=151016/fractured-necrolyte-skull) that I use somewhat often, not sure if that would fit in somewhere as well.

Ty for the addon!

**Comment by Justw8** [comment]
This is a scary hole - also would need to figure out how to display it properly. 
Sticking with just the toys/dungeon tps right now but I am fully open to add more items, so leaving this open for more suggestions of items to add.

**Comment by Justw8** [comment]
closing this and opening a general list I'll try to keep track of all missing items that I'll plan on adding when the time is right. :)
