### ISSUE TITLE
The first time you open Options you get an error.

### ISSUE THREAD

**Issue by nanjuekaien1** [Justw8/TeleportMenu#21]
Interface/AddOns/TeleportMenu/Options.lua:95: attempt to concatenate field 'name' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@Interface/AddOns/TeleportMenu/Options.lua"]:95: in function <Interface/AddOns/TeleportMenu/Options.lua:88>
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua"]:528: in function <...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:527>
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua"]:558: in function <...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:554>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_Menu/Menu.lua"]:2417: in function `PopulateDescription'
[string "@Interface/AddOns/Blizzard_Menu/DropdownButton.lua"]:252: in function <Interface/AddOns/Blizzard_Menu/DropdownButton.lua:251>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_Menu/DropdownButton.lua"]:262: in function `GenerateMenu'
[string "@Interface/AddOns/Blizzard_Menu/DropdownButton.lua"]:247: in function `SetupMenu'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua"]:554: in function `InitDropdown'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingControls.lua"]:538: in function `SetupDropdownMenu'
...
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsList.lua"]:140: in function `Display'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:845: in function `DisplayLayout'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:807: in function `DisplayCategory'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:749: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:742>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_Settings_Shared/Blizzard_CategoryList.lua"]:152: in function <...s/Blizzard_Settings_Shared/Blizzard_CategoryList.lua:150>

**Comment by Justw8** [comment]
Please try out the latest alpha.

**Comment by Justw8** [comment]
Please try out `v7-8-gfbeb355`

**Comment by nanjuekaien1** [comment]
perfect
