### ISSUE TITLE
Addon only shows Hearthstone and Bonus Hearthstone (which does not expand)

### ISSUE THREAD

**Issue by Rikutheal** [Justw8/TeleportMenu#25]
![image](https://github.com/user-attachments/assets/f1dbde5e-17f2-41d5-af07-3192d5e5cec4) 

Ever since the last update my addon has been like this- I have basically every hearthstone toy; all of the engineer portals and most of the obtainable portals. If there is any other information I can provide to help solve this issue let me know.

**Comment by Justw8** [comment]
If you could provide the lua errors related this this that would be helpful, besides that I can only recommend to revert back to V7 and not the latest alpha. 
A reload would likely also work - but not ideal.

**Comment by Rikutheal** [comment]
![image](https://github.com/user-attachments/assets/f112b2f4-e985-4b9d-8724-65cb4a8876cf)

I thought it wasn't producing a LUA error but I guess it is.

**Comment by Justw8** [comment]
Please try out `v7-8-gfbeb355`

**Comment by Rikutheal** [comment]
No errors and a full menu on v7-8!
