### ISSUE TITLE
Menu not showing up

### ISSUE THREAD

**Issue by Voigash** [Justw8/TeleportMenu#29]
The menu is not showing up at all.
Attempted uninstall, reinstall, and changing versions without any difference.
The /tpm menu works, but won't save changes. if i enable/disable the addon trough the addon menu nothing happens.

Version: 
* TeleportMenu-v8 (11.0.2)
* TeleportMenu-v8-1-gf7e4f13 (11.0.2)

**Comment by Justw8** [comment]
pushed a v8.1 that should fix it, was an issue loading the savedvariables for first time users. Thanks for reporting!
