### ISSUE TITLE
Add a seperate button for hearthstones not sharing a cooldown.

### ISSUE THREAD

**Issue by jparac** [Justw8/TeleportMenu#3]
[Stone of the Hearth](https://www.wowhead.com/item=212337/stone-of-the-hearth) toy acts as a hearthstone, but its cooldown is separate from default hearthstone. It would be cool to include it separately in the list

**Comment by Justw8** [comment]
Did not know this! I can add it as a seperate toy/hs.

**Comment by Justw8** [comment]
While investigating, there are more hearthstones that share the cd with Stone of Hearth, will setup a seperate section/button for those sharing this 'bonus' cooldown when I get to it, was more work then just moving it to seperate buttons. 

(so far I've read:
Stone of the Hearth

**Comment by Justw8** [comment]
I've split up the hearthstones, if any of them share cd again or there are more that don't, please let me know!
