### ISSUE TITLE
Allow Covenant Hearthstones when requirements are met for x-covenant usage

### ISSUE THREAD

**Issue by Coyle19** [Justw8/TeleportMenu#34]
The shadowlands covenant-based hearthstones are missing from the basic options menu, unless it is the Covenant your character is a part of. ie if I'm a Necrolord, the option to use the Necrolord hearth shows up. If I'm not in a covenant (Didn't do shadowlands) none of these hearths show up. 

These hearths are usable regardless of having done shadowlands or being in the Covenant (The description text on the toy's are just incorrect)

I also assume the randomizer doesn't pick these under the same circumstances as I've never seen it choose one for a Covenant I'm not a part of

**Comment by Justw8** [comment]
I get an error when using the covenant toy of a covenant I'm not part of. <_<

**Comment by Coyle19** [comment]
> I get an error when using the covenant toy of a covenant I'm not part of. <_<

Ah that's right, I forgot there is a requisite for it. I actually went to look it up. 'Covenant cosmetics are unlocked account-wide once you reach 80 renown with that covenant.' This means the achievement 'Re-re-re-Renowned' would confirm access to these cosmetics across the account

**Comment by Justw8** [comment]
I see, I will update it when I find the time! progress is about to start, so this will be some weeks before I get to it.

![image](https://github.com/user-attachments/assets/cd8902c1-7bf7-4ba6-a273-5567e64a9c1a)

**Comment by Justw8** [comment]
Should be added in the latest alpha / next release!
