### ISSUE TITLE
Druid in travel form

### ISSUE THREAD

**Issue by granmark** [Justw8/TeleportMenu#36]
Could you make it so a click on a hearthstone shifts druids into a form which can cast it (now gives an error)? The sequence of: Escape -> Click Hearthstone (error) -> Escape (to close menu) -> Shapeshift to form which can cast hearthstone -> Escape -> Click hearthstone, is somewhat annoying.

**Comment by Justw8** [comment]
The buttons are secure buttons, this means I can only use the action it's assigned too. So this is not something I will (and cant afaik) implement.
