### ISSUE TITLE
Multiple icon rows

### ISSUE THREAD

**Issue by jparac** [Justw8/TeleportMenu#39]
Some teleport options such as mage portals/teleports have quite a bit of icons in a single row. Would it be possible to add wrap option so that icons span multiple rows after certain count

<h3>How it looks now</h3>

![Screenshot 2024-09-23 212306](https://github.com/user-attachments/assets/753f720e-a084-41e4-832b-7126f5054727)

<h3>With wrap</h3>

![Screenshot 2024-09-23 211953](https://github.com/user-attachments/assets/82c198ab-a950-4a22-a1fa-8f6675f49c4c)

**Comment by Justw8** [comment]
yep, on the todo list 👍

**Comment by Justw8** [comment]
Let me know if it's working as intended!
