### ISSUE TITLE
Suggestion : Different Expansion Icons

### ISSUE THREAD

**Issue by PreYem** [Justw8/TeleportMenu#4]
I'm loving the add-on so far, but I suppose a different set of Icons for each expansion icon would be better, as the current ones are slightly confusing, I know they're sorted from top to bottom based on which expansion came first, but just a suggestion nonetheless though, also making the icons a tiny bit smaller and/or perhaps movable while the Escape menu is on.

Thank you for this add-on nonetheless!

**Comment by Justw8** [comment]
Heya, if you have suggestions for better icons please link them here!

**Comment by PreYem** [comment]
Certainly, here's some of my personal suggestions, feel free to pick whichever you like best, or ignore all together if it doesn't fit well :

Dragonflight :
- https://www.wowhead.com/icon=4622500/inv-companionpterrordaxdrake
- https://www.wowhead.com/icon=4696175/ui-dracthyr
- Current icon is alright as well

Shadowlands : 
- https://www.wowhead.com/icon=4062765/achievement-raid-torghastraid
- https://www.wowhead.com/icon=3642306/inv-torghast

Battle For Azeroth :
- https://www.wowhead.com/icon=3194610/achievement-nzothraid-nzoth
- https://www.wowhead.com/icon=1869493/inv-heartofazeroth

Legion :
- https://www.wowhead.com/icon=1260827/classicon-demonhunter
- https://www.wowhead.com/icon=1305156/ability-demonhunter-eyebeam
- https://www.wowhead.com/icon=1711456/inv-argusfelstalkermountred

Warlords of Draenor :
- https://www.wowhead.com/icon=1413856/achievement-thenighthold-guldan
- https://www.wowhead.com/icon=1005700/achievement-boss-blackhand#
- https://www.wowhead.com/icon=1113431/achievement-boss-hellfire-archimonde#

Mists of Pandaria :
- https://www.wowhead.com/icon=5690106/ability-mount-pandarenphoenix-white
- https://www.wowhead.com/icon=656166/inv-celestialserpentmount
- https://www.wowhead.com/icon=656169/inv-pandarenserpentgodmount-black

Cataclysm : 
- (Couldn't find a direct icon link on wowhead) --> https://www.wowhead.com/item=172012/obsidian-worldbreaker


I also just came to notice that the expansions aren't sorted by date, I had : 
DF - Legion - BFA - WoD - MoP - Cata, in that order, although I don't have SL portals on my account so I'm not sure if it's not sorted just because of me or not.

**Comment by Justw8** [comment]
Could you show a screenshot of that order? it should be hard-set in expansion order.

**Comment by Justw8** [comment]
And thanks for the suggestions!

**Comment by PreYem** [comment]
Here's a screenshot of the order I have on my game, again I don't have any SL portals, so not sure if that's the issue or not.
![Untitled](https://github.com/user-attachments/assets/8db12849-4a96-4632-bf81-bafeb20cb53f)

**Comment by Justw8** [comment]
BFA and legion are swapped around, the rest seems fine at least 👍  will fix

**Comment by PreYem** [comment]
A small issue I've noticed just now :
You have your Hearthstone, which is usable by any character at any point in the game, regardless of level or quest progress, but the same can't be said about the Garrison/Dalaran Hearthstones, as those require a brief intro questline for their respective expansions to be usable, otherwise the icons on the menu are not very useful except being a reminder to do the WoD/Legion intro questlines, so some kind of script that checks if the character currently logged on has finished the intro questline and only show those Hearthstones can fix this issue, here are the quests that make those Hearthstones usable :

WoD Garrison Hearthstone :
- Alliance Side : https://www.wowhead.com/quest=34586/establish-your-garrison
- Horde Side : https://www.wowhead.com/quest=34378/establish-your-garrison

Legion Dalaran Hearthstone : (There are also 2 instances of this quest for some reason, not sure why)

- https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye
- https://www.wowhead.com/quest=44663/in-the-blink-of-an-eye

This issue might be too much of a hassle to fix, so feel free the skip it entirely if it's the case.

**Comment by Justw8** [comment]
I think it should be simple to check if one of the quests is completed and if not, hide the toy icon.

**Comment by Justw8** [comment]
I've updated the icons for expansions with some of your suggestions, 

Also added the check for the quests for Garrison and Dalaran heartstones, thanks again!
