### ISSUE TITLE
Suggestion: Add Row for Current Season M+ Teleports

### ISSUE THREAD

**Issue by Parks3389** [Justw8/TeleportMenu#40]
Hi Justw8,

Could we have an additional row that puts the current M+ season's teleports in its own row? 

And/or could there be a checkbox in the options that would replace all the "Hero's Path" teleports with just the current season teleports? 

Thank you!

**Comment by jetersen** [comment]
@Parks3389 I created #41 and added a option. Feedback would be appreciated :smile:
