### ISSUE TITLE
Teleport text only considers some dungeons (Rotation ones maybe?)

### ISSUE THREAD

**Issue by EraxterCodes** [Justw8/TeleportMenu#48]
After #38 we got some text on teleports which looks very nice! I like it.

I have 2 pieces of friendly feedback however. 

Firstly Is it possible to have the toggle in the options update imideitaly instead of waiting for a /reload? Perhaps a function could be added that allows you to rerender all the buttons so you don't have to save all the buttons references in order to make a "updateX" function?

Secondly It seems to only consider some dungeons. If you are on a character that did Challenge modes those do not have any text associated with them(see screenshot only the WoD dungeons that have been part of rotation have text)
![image](https://github.com/user-attachments/assets/2093205f-bdfa-45aa-bae2-c99dadb1790b)

This looks a bit odd is all.

**Comment by Justw8** [comment]
Sounds like the table is incomplete still. Will look at it at some point.

**Comment by kayti-wow** [comment]
Sorry about that.  I didn't have any of the challenge mode dungeon teleports to test with and couldn't find the spellids. @EraxterCodes could you share the spell name on the tooltip for each missing one, please?

**Comment by EraxterCodes** [comment]
@kayti-wow  Sure

**MoP**

- Path of the Stout Brew - 131205
- Path of the Shado-Pan - 131206
- Path of the Mogu King - 131222
- Path of the Setting Sun - 131225
- Path of the Scarlet Blade - 131231
- Path of the Scarlet Mitre - 131229
- Path of the Necromancer - 131232
- Path of the Black Ox - 131228

**WoD**

- Path of the Bloodmaul - 159895
- Path of the Vigilant - 159897
- Path of the Skies - 159898
- Path of the Burning Mountain - 159902

**Comment by Justw8** [comment]
Updated the missing ones from above, also added some raid ones. More are missing but I added a print so people can report it.
