### ISSUE TITLE
ShowOnlySeasonalTeleports also hides Mage portals 

### ISSUE THREAD

**Issue by EraxterCodes** [Justw8/TeleportMenu#49]
After #41 Was merged we got a lot less clutter on the teleportmenu which is super nice, however it also hides the mage teleports and portals 
![image](https://github.com/user-attachments/assets/8ce8d9e7-939e-4437-8d70-325dcb719007)

I wonder if this was intentional? Hearhstone is preserved so I'm guessing this might just be an oversight? Perhaps CreateHeroPathFlyouts could be changed to have a check for mage portals and teleports? Or better yet HeroPaths and mage portals/teleports could be separate functions?

Also just like #48 It would be nice if the toggle for this feature toggled instantly rather than waiting for a /reload

**Comment by Justw8** [comment]
Should be fixed.
