### ISSUE TITLE
Any way to change the size of the buttons ? 

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [Justw8/TeleportMenu#6]
They seem massive to me

**Comment by Justw8** [comment]
not yet, will add this when I make an option menu.

**Comment by Lawdie** [comment]
Second this, for me the buttons are so big portals and teleport options run off the edge of the screen. I can't currently click the teleport / portal to Dornogal as its off screen 

![image](https://github.com/user-attachments/assets/443ced51-a2de-4763-a52b-1e8aadcbb02b)

**Comment by Justw8** [comment]
lmao! I could also add a max-limit on the buttons for this, so it would start another row after X buttons. Prolly a good idea.

**Comment by Justw8** [comment]
Added a re-size option, always squares for now.
