### ISSUE TITLE
Bonus Hearthstones in 11.0.5

### ISSUE THREAD

**Issue by JbBerry** [Justw8/TeleportMenu#60]
Bonus Hearthstones (Tome of Town Portal & Stone of the Hearth) now share cooldown with all other hearthstone toys.
Is it possible to remove the Bonus Hearthstone section and add these to the allowed toys for the main heathstone button?

**Comment by Justw8** [comment]
I wonder if the same goes for https://www.wowhead.com/item=210455/draenic-hologem#comments

Anyone have this hs? >_>

**Comment by Justw8** [comment]
All bonus hearths are removed until further notice.
