### ISSUE TITLE
[Non-EN clients errors] /tp or /tp list not working

### ISSUE THREAD

**Issue by SirVossler** [Justw8/TeleportMenu#7]
I'm using the pt_BR client and the commands don't work (I don't know if it's related to the language, since no one has reported this yet).
When I type both commands, chat shows: "You are not part of a group".

**Comment by ZodPTR** [comment]
Message: Interface/AddOns/TeleportMenu/TeleportMenu.lua:387: attempt to concatenate local 'name' (a nil value)
Time: Fri Aug 23 14:23:33 2024
Count: 6
Stack: Interface/AddOns/TeleportMenu/TeleportMenu.lua:387: attempt to concatenate local 'name' (a nil value)
[string "@Interface/AddOns/TeleportMenu/TeleportMenu.lua"]:387: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5468: in function <...AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5414>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5120: in function <...AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5119>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5156: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals: msg = "list"
(for state) = <table> {
 166747 = true
 209035 = true
 162973 = true
 165802 = true
 212337 = true
 163206 = true
 93672 = true
 190196 = true
 168907 = true
 200630 = true
 142542 = true
 206195 = true
 208704 = true
 163045 = true
 193588 = true
 64488 = true
 166746 = true
 172179 = true
 165669 = true
 188952 = true
 190237 = true
 54452 = true
 165670 = true
}
(for control) = 200630
id = 200630
_ = true
_ = 200630
name = nil
(*temporary) = 200630
(*temporary) = " - "
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'name' (a nil value)"
APPEND = "TeleportMenu: "
validHearthstoneToys = <table> {
 166747 = true
 209035 = true
 162973 = true
 165802 = true
 212337 = true
 163206 = true
 93672 = true
 190196 = true
 168907 = true
 200630 = true
 142542 = true
 206195 = true
 208704 = true
 163045 = true
 193588 = true
 64488 = true
 166746 = true
 172179 = true
 165669 = true
 188952 = true
 190237 = true
 54452 = true
 165670 = true
}
availableHearthstones = <table> {
 1 = 209035
 2 = 183716
 3 = 165802
 4 = 212337
 5 = 200630
 6 = 142542
 7 = 165669
 8 = 188952
 9 = 190237
 10 = 165670
}

**Comment by Justw8** [comment]
@ZodPTR are you also on another client's language? It's trying to print a toy name but can't find it. :(

**Comment by Sohen** [comment]
same "you're not in a party" chat message with french client

no error in bugsack, not sure where you got this from @ZodPTR or if you have another issue

**Comment by ZodPTR** [comment]
> @ZodPTR are you also on another client's language? It's trying to print a toy name but can't find it. :(

I'm using EN client

**Comment by javierhimura** [comment]
The same problem happens with Spanish Client. I can't use the command /tp from the addon, it seems /tp is a command related to group content in the main game, but I am not sure what this command do, nor what it is the equivalent on other langauges

**Comment by Justw8** [comment]
the chat commands do not interact with party content at all, there's only `PlayerHasToy()` and `GetToyInfo()` in there, so unsure what causes this. I'll try it myself by changing the client when I get time. Sorry for the inconvenience!

**Comment by javierhimura** [comment]
> the chat commands do not interact with party content at all, there's only `PlayerHasToy()` and `GetToyInfo()` in there, so unsure what causes this. I'll try it myself by changing the client when I get time. Sorry for the inconvenience!

It is not the addon command the one that interacts with party content, it is a command available in Blizzard's UI, but only in some client languages. That is why in languages in wich /tp is not a Blizzard's command it could be used as an addon's command, but in languages in witch Blizzard have that command it is not possible for the addon to register the command. I suppose the solution would be to have the addon register an additional command like /teleport, wich is not used by Blizzard (/tm is also used by Blizzard so it isn't an option)

**Comment by Justw8** [comment]
I see, The more you know! I'll have to adjust the command then. there is a secondary command already available: `/tpmenu` this might work then for now.

In the future I'll just be adding an option menu and the chat commands wont be used at all.

**Comment by Justw8** [comment]
I've updated the short command to `/tpm`, please open a new ticket if the issues continue after updating to v5+

**Comment by Justw8** [comment]
@ZodPTR if your issues is still happening too, please open a new ticket with more information.
