### ISSUE TITLE
Missing Teleports

### ISSUE THREAD

**Issue by DragonessAbivelus** [Justw8/TeleportMenu#8]
Fantastic add on- thank you.

Missing for me are:

TOYS:
Wormhole Centrifuge
Wormhole Generator: Argus
Wormhole Generator: Kul Tiras
Wormhole Generator: Northrend
Wormhole Generator: Pandaria
Wormhole Generator: Zandalar

ITEMS
Flight Masters Whistle
Lucky Tortollan Charm
Potion of Deepholm

EQUIPMENT
Signet of the Kirin Tor
Cloak of Coordination 
Wrap of Unity
Shroud of Cooperation

**Comment by Justw8** [comment]
Wormholes should already be added in the latest version.

I'll have to think about how to properly display and order the buttons and items better before adding all of them, the equipment also has the added problem of needing to be equipped. 

Wont say never, but not very soon for those.

**Comment by DragonessAbivelus** [comment]
> Wormholes should already be added in the latest version.
> 
> I'll have to think about how to properly display and order the buttons and items better before adding all of them, the equipment also has the added problem of needing to be equipped.
> 
> Wont say never, but not very soon for those.

I understand the equipment might be more difficult due to needing to be equipped first. Will the items be implemented any time soon?

Maybe I'm not seeing the toys because of an added conflict. I'm using Postal and ConsolePort (I know Console Port changes the menu, maybe it's that?)

**Comment by Justw8** [comment]
Nope, they only show up if you actually have the required skills in engineering to use them though. (and might require a relog/reload after learning the skill)

**Comment by Justw8** [comment]
I've added all missing wormholes as far as I know, items are on hold until I create an option menu / flyout / filter before I start filling up the limited space I want to keep working with. Closing this to just have 1 ticket open for this :)
